### ISSUE TITLE
Add website URL to website on github

### ISSUE THREAD

**Issue by abdullahi-abubakar** [Irene-24/react-news-app#1]
Hello irene its omolajacodec i find it hard to view your website immediately i check your news repository until I clone  your repository .
why don't you add the website to your repo so that i can view it immediately just add http://my-news-app.surge.sh to the website bar

**Comment by Irene-24** [comment]
> Hello irene its omolajacodec i find it hard to view your website immediately i check your news repository until I clone your repository .
> why don't you add the website to your repo so that i can view it immediately just add http://my-news-app.surge.sh to the website bar

I have added it now. Thanks for the review
